wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704728080.497625
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
